### ISSUE TITLE
Data reception peaks, doubt

### ISSUE THREAD

**Issue by pha377** [zaphoyd/websocketpp#1005]
I am using websocketpp with asio-tls

My program receives messages through `on_message` callback. The messages contains states of a sensor, (`datetime-state-param1-param2-param_n`),  that are sent to a function for processing (storage, comparisons, etc.)

At certain times (from 1 second to 30 seconds), it receives many states, which the computer is not able to process as fast as they arrive.

I wonder what happens to the data not yet processed? is it buffered? is it lost?

My doubt is if I am losing states, or are they processed later.

I guess there is a receive buffer, Is the receive buffer sized? 
Can that size be modified, consulted, enlarged?

Thanks

**Comment by zaphoyd** [comment]
The incoming data rate will be modulated via TCP flow control. There is minimal buffering for reads. Because TCP is used there shouldn't be any data loss during the WebSocket connection itself. As such the sending side will be prevented, via TCP flow control, from writing faster than the receiving end can read it. If data is generated on the source faster than the recieving processor can handle it you have some options:

- Buffer at the source. This depends on the implementation of the source. If the source is a WebSocket++ program then the default behavior is to buffer outgoing messages indefinitely as long as there is memory. This is configurable and queryable. You can also implement your own buffer in front of WebSocket++ which might be more efficient if you are pushing data out to many clients.

- Buffer manually at the processor, after the message handler. If the bottleneck is in _processing_ rather than merely reading the data you can write your receiving message handler to just buffer data for later processing yourself. You will return from the message handler as soon as possible so it can get back to reading. You can then clear out your processing buffer either in another thread or during network quiet times.

**Comment by pha377** [comment]
Thank you Peter !!
