### ISSUE TITLE
This project designed to work on Windows?

### ISSUE THREAD

**Issue by kazumasa-kusaba** [zaphoyd/websocketpp#1026]
I tried building [examples](https://github.com/zaphoyd/websocketpp/tree/master/examples), but build errors occurred.  It seems that functions not defined on Windows are used.   
  
For example:  
https://github.com/zaphoyd/websocketpp/blob/1b11fd301531e6df35a6107c1e8665b1e77a2d8e/examples/print_client_tls/print_client_tls.cpp#L71
  
Does this project designed to work on Windows? Or I can't build only [examples](https://github.com/zaphoyd/websocketpp/tree/master/examples) itself on Windows? Can I build [websocket](https://github.com/zaphoyd/websocketpp/tree/master/websocketpp) itself?  
  
Is there anything in the [documentation](https://docs.websocketpp.org/) about the supported OS?

**Comment by barsnick** [comment]
Which compiler are you using?

Here's a hint about `strcasecmp()`, which is POSIX:
https://stackoverflow.com/questions/3694723/error-c3861-strcasecmp-identifier-not-found-in-visual-studio-2008

**Comment by zaphoyd** [comment]
WebSocket++ itself should definitely work with Windows and Visual Studio. Most of the bundled examples should as well, but it is possible that some do not because they demonstrate the use of certain posix-y things (like syslog). In the case of `print_client_tls` it does look like, as @barsnick notes, it is using a the non-STL POSIX function `strcasecmp()`. I'll make a note, as this example should be possible to be made cross platform.

**Comment by kazumasa-kusaba** [comment]
@barsnick @barsnick   
Thank you! I'll try it later!
