### ISSUE TITLE
can the websocketpp::client<websocketpp::config::asio_client> be a http client

### ISSUE THREAD

**Issue by Hyatt-Zhong** [zaphoyd/websocketpp#1047]
hello ,i use the client send a http POST METHOD MESSAGE,the server on_message handle response,not the on_http handle response. 
So,  can the client be a http client? or is there any httpclient example ? 

expect reply and thank you so much.

**Comment by zaphoyd** [comment]
WebSocket++ does not include a general purpose HTTP client. There are lots of other good HTTP client libraries if you need one. WebSocket++ does include a limited HTTP server capability (which uses the http handler you mention) because unlike clients, it is more difficult to run both an HTTP server and a WebSocket server on the same port. The built in HTTP server is fairly simple though and if you are doing heavy duty HTTP work I would recommend using Apache or Ngnix and proxying the WebSocket connections to your WebSocket++ application.
