### ISSUE TITLE
Unable to send messages immediately

### ISSUE THREAD

**Issue by DKGH** [zaphoyd/websocketpp#1093]
I have a message handler for my server which looks like this:

```
void MessageHandler(const websocketpp:connection_hdl& handle_, const websocketpp::server<websocket::config::asio>::message_ptr& message_)
{
  const auto& connection = m_server_instance.get_con_from_hdl(handle_);
  const auto& progressUpdate = [&connection](const std::string& update)
  {
    auto& socket = connection->get_socket();
    socket.set_option(websocketpp::lib::asio::ip::tcp::no_delay(true));
    socket.lowest_layer().set_option(websocketpp::lib::asio::ip::tcp::no_delay(true));
    connection->send(update);
    connection->write_frame();
  }
  ProcessMessageWithRegularProgressUpdates(message_, progressUpdate);
}
```

Here the ProcessMessageWithRegularProgressUpdates is expected to send some updates periodically. However, the updates are getting queued up and all of them are being sent in a burst towards the end. Based on some previous posts, I introduced ```no_delay(true)```. However, that doesn't seem to help.  ```connection->write_frame();``` dispatches just the first update. But the rest of them arrive in a bunch. What am I missing here?

**Comment by zaphoyd** [comment]
Is process with updates performed on another thread to asynchrony task? If not it will run synchronously, produce and queue all the update messages before ever returning control back to the library to write.

connection-write_frame definitely shouldn’t be called here.

not directly related to this issue, but I’d recommend just setting tcp no delay once, either in the open handler or socket unit handler, it applies for the duration of the connection.

if you use a thread or async task to run your processing function I’d also recommend capturing the connection hdl rather than the full connection pointer and using endpoint::send (this helps ensure proper behavior when multiple threads are in use)

**Comment by DKGH** [comment]
It is difficult for me to multithread the task without significant cross thread access violations. Is there an async send?

**Comment by zaphoyd** [comment]
Send is async, which basically is the problem. There isn't a sync send, because Asio and Websocket++ generally are designed to be used in an async environment.

To use this pattern (single thread cooperative multitasking) without threads you would do something like...

message handler
- store the details of the request somewhere
- start an async task (using the interrupt handler or timer handler) that will read request details and completion state and perform one chunk of work, send a status update, and then queue the next chunk of work
- yield (allow the message handler to return)

this returns control to the Asio event loop and allows it to process incoming and outgoing messages asyncronously and periodically call your async task (again, via the interrupt or timer handlers) to progress that task. When the task is complete the final invocation simply declines to re-queue a timer/interrupt and the task ends.

**Comment by DKGH** [comment]
Okay. Actually, converting captures for lambdas from reference to non reference took care of most of it. It wasn't that much after that. Problem solved for now.
