### ISSUE TITLE
Why not all occurrences of m_internal_state and m_state are under lock?

### ISSUE THREAD

**Issue by justanotheruser** [zaphoyd/websocketpp#417]
Hello and sorry for possibly bad english. I'm currently invesigating crash that happened during high load on our program (which uses websocketpp). We're currently using version 0.3. Looks like reason of crash is similar with this https://github.com/zaphoyd/websocketpp/issues/389 We decided to upgrage to more recent version, that uses internal state machine to prevent illegal actions like receiving handshake responce in closed state. This machine uses m_internal_state to track it's state, and just under it's definition there's comment 'Lock: m_connection_state_lock', but it doesn't locked in all places. I want to know why this is safe, just to be sure this error wouldn't happen again.

**Comment by zaphoyd** [comment]
The `m_internal_state` value is never explicitly locked because it is only accessed via handlers within the given connection's strand of execution. The asio io_service strand object serializes all handlers associated with that connection, even when multiple threads are processing io_service handlers.
