### ISSUE TITLE
Two SSL records for one message.

### ISSUE THREAD

**Issue by amdei** [zaphoyd/websocketpp#424]
Hello,

I wrote a programm using Websocket++, what exchange mesages between client and server.
I didn't use any embeded transports, but use library in iostream manner, handling send and receive by myself.

Whenewer I call client.send(), I got two writes in my write handle, set by set_write_handler().
First for hrader, and second - for message body.

As a result, I got two SSL records in channel.
What produces unnecessary overhead. Two bytes of header results in may bytes of SSL record.

I, as a library user, would prefer to get in write handle complete message, with header, body and footer (if any), so I can wrap it into single SSL record.

**Comment by zaphoyd** [comment]
As you've noticed, WebSocket++ writes header and payload to the transport layer separately. The reason is to avoid having to copy the message directly behind the variable length header before writing. In addition, to improve efficiency in situations like you describe (wanting to use as few TCP packet and TLS segments as possible), WebSocket++ may write multiple messages at once to the transport layer.

The Asio transport understands how to deal with this and will write the headers/payloads for multiple messages in a single TCP packet / TLS segment. Until recently, implementing this behavior with the iostream/raw transport was more difficult. The next version (0.6.0) will include a vector write handler as an option that will provide a vector of buffers that should be written as a single operation (i.e. coalesced into as few wrapping TCP/TLS/etc calls as possible). This is implemented on the `develop` branch now if you want to play around with it. See `transport::iostream::connection set_vector_write_handler` (https://github.com/zaphoyd/websocketpp/blob/develop/websocketpp/transport/iostream/connection.hpp#L354).

**Comment by zaphoyd** [comment]
The 0.6.0 release contains the necessary vectored write handler to fix this issue.
