### ISSUE TITLE
Segmentation fault on MacOS X 10.11

### ISSUE THREAD

**Issue by maxoodf** [zaphoyd/websocketpp#473]
Hello,
I am looking for a C++ WebSocket library to replace Qt5 WebSocket implementation and its dependencies.
I have the following problem. I started with debug_client example and it crashes on 
connection_impl.hpp:431 - "return m_uri;"
with EXC_BAD_ACCESS exception.

PS Build with -DWEBSOCKETPP_STRICT_MASKING did not help...

**Comment by maxoodf** [comment]
And some info about my build environment:


bash-3.2$ clang++ --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

bash-3.2$ openssl version
OpenSSL 1.0.2d 9 Jul 2015

bash-3.2$ brew info boost
boost: stable 1.58.0 (bottled), HEAD
Collection of portable C++ source libraries
http://www.boost.org
/usr/local/Cellar/boost/1.57.0 (10572 files, 439M)
  Poured from bottle
/usr/local/Cellar/boost/1.58.0 (10718 files, 478M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb
==> Dependencies
Optional: icu4c ✔
==> Options
--c++11
	Build using C++11 mode
--universal
	Build a universal binary
--with-icu4c
	Build regexp engine with icu support
--with-mpi
	Build with MPI support
--without-single
	Disable building single-threading variant
--without-static
	Disable building static library variant
--HEAD
	Install HEAD version

**Comment by zaphoyd** [comment]
Hi, the problem here is not in the library, but rather in that example code. As mentioned in the comments at the time, the debug_* examples are used as scratch examples for testing and debugging purposes and may not always be updated perfectly to reflect library changes.

In this case, what is happening, is that the error code from get_connection() is being checked, the error printed, but execution doesn't end there as it should. Instead the program continues in a broken state, resulting in the crash. I'm pushing an update to the dev channel that fixes this for now.

**Comment by zaphoyd** [comment]
This issue in the examples has been corrected.
