### ISSUE TITLE
stop_listening() with many errors

### ISSUE THREAD

**Issue by ChristianRobl3D** [zaphoyd/websocketpp#498]
My server project needs to pause and stop accepting / listening connections in some cases.
I'm calling stop_listening() on my web server and gent those errors:
[2015-12-22 17:09:21] [info] Error getting remote endpoint: system:9 (Bad file descriptor)
[2015-12-22 17:09:21] [info] handle_accept error: Operation canceled
[2015-12-22 17:09:21] [info] Stopping acceptance of new connections because the underlying transport is no longer listening.
[2015-12-22 17:09:21] [info] asio async_shutdown error: asio.ssl:336462100 (uninitialized)

This happens regardless if the server was just freshly started without any client connection of if there are one or more connections to it.

I resume the server via: listen() and start_accept() and everything seems fine.

Now, I'd like to know why the errors are and whats the best way to avoid them and I also occasionally get exceptions (asio related), which currently brin my server down (I (yet) was not able to debug those exceptions).

I'm using websocketpp 0.6.0 and boost 1.59.0.

Any help very much appreciated!

Thank you very much!

**Comment by zaphoyd** [comment]
At the moment, a new connection is created containing the socket that listen will accept into. When you stop listening, this pending connection gets deleted. This produces a situation that looks like errors but is in fact expected. These notices are included on the information logging channel rather than the error log (as they would if they failed for other reasons).

At some point this will probably change such that only the socket itself needs to be created rather than a whole pending connection. I need that behavior for another feature request that allows sockets to be accepted by the user and then passed, already accepted into WebSocket++. Until that point this behavior is expected, you can safely ignore those information notes.

There have been a few few connection canceling related exceptions fixed on the develop branch. Can check that out and tell me if it fixes your exception issue? The library should not throw any exceptions from the run/asio handler methods, so if you are getting some, that is a bug.

**Comment by ChristianRobl3D** [comment]
I just gave the development branch some test runs: I can't tell absolutely for sure, but I haven't seen the exceptions popping up again - looks promising!

I'll do some more test (also cross check using 0.6.0) with it after the christmas break and give a short info here, of course.

Thank you for the information on the [info] error/warnings regarding stop_listening().

Happy holidays!

**Comment by zaphoyd** [comment]
Closing this as it seems to be resolved. Please reopen if that is not the case

**Comment by hussainabidi1** [comment]
```cpp
[2024-07-19 22:01:05] [info] Error getting remote endpoint: system:9 (Bad file descriptor)
[2024-07-19 22:01:05] [fail] WebSocket Connection Unknown - "" - 0 websocketpp:26 Operation canceled
[2024-07-19 22:01:05] [info] asio async_shutdown error: system:9 (Bad file descriptor)
[2024-07-19 22:01:05] [info] handle_accept error: Operation canceled
[2024-07-19 22:01:05] [info] Stopping acceptance of new connections because the underlying transport is no longer listening.```

I am getting this error after I run `stop_listening()`
