### ISSUE TITLE
Could this websocket client run on Unreal Engine 4?

### ISSUE THREAD

**Issue by chelinho139** [zaphoyd/websocketpp#521]
Hey this is more like a question than an issue:

Could this websocket client run on Unreal Engine 4?

I know you can use c++ so i dont really now..

**Comment by zaphoyd** [comment]
Generally the mailing list (websocketpp@googlegroups.com) is preferred for non-issue questions.

I really don't know much about how Unreal Engine works. WebSocket++ has fairly flexible dependency management and has pluggable network transport policies that could be used, if for example Unreal Engine wanted to handle all the network parts and you just needed the websocket protocol parsing.... Really depends on how Unreal Engine works though.

**Comment by MaxFights** [comment]
That is exactly what I am trying to do now, I have been having a headache so far (that's only because I'm new to everything) but what I really need to do is to use UE4 as a client, all I want to do is to be able to send and receive JSON strings. I will be writing the server in another language though so I just need client functionality.

I'm pretty new to C++ and I'm not very good, I understand that I need to include and link some stuff in order to use the libraries. If I could link the libraries, it would be possible to write some stuff that will allow me to call functions that control websocket connections in blueprint (Unreal's visual scripting language) and that would be awesome.

Is there any way you could take a look at this guide which explains how to link external libraries to Unreal Engine?

https://wiki.unrealengine.com/Linking_Static_Libraries_Using_The_Build_System

If you could help me out that would be amazing, because if I can't get websockets to work with Unreal Engine, then I will have to turn to HTTP long polling.

**Comment by zaphoyd** [comment]
This is a usage/support related question/discussion. Not a bug or feature request. The mailing list for usage related questions & discussions is websocketpp@googlegroups.com.
