### ISSUE TITLE
Connect through cloudflare

### ISSUE THREAD

**Issue by wbdn** [zaphoyd/websocketpp#546]
Hello! How can I connet to site through cloudflare?
When I trying to connect secure i got: ```could not create connection because: endpoint not secure```
If I'll connect to ws then I got something like this [img](http://i.imgur.com/1iWORLt.png?1)

**Comment by zaphoyd** [comment]
the endpoint not secure error is because you tried to connect to a wss url using a plain/non-TLS encrypted endpoint. To fix that, use an encrypted endpoint config.

The error from the image (websocket version -2) indicates a rare condition where the handshake completed before a valid HTTP request was complete. To debug that further I would need either a packet capture, or the log output with the `devel` / `debug_handshake` / `debug_close` channels turned on. (see http://docs.websocketpp.org/reference_8logging.html and http://docs.websocketpp.org/reference_8config.html for details on how to do this)
