### ISSUE TITLE
How to send binary data more elegant?

### ISSUE THREAD

**Issue by stavenko** [zaphoyd/websocketpp#572]
Hello,
I just found out, how to send four floats into websocket:

      float values[4] = {1.1, 2.2, 3.3, 4.4};
      std::string resp;
      resp.reserve(sizeof(float) * 4);
      resp.assign(reinterpret_cast<char*>(values), sizeof(float)*4);
      s->send(hdl, resp, websocketpp::frame::opcode::binary);

But this seems to me a little bit scary, maybe we have some special case, in which we could send binary data in little more elegant way? Did I miss something?

**Comment by zaphoyd** [comment]
A few notes:

There is not need to convert to a string, you can send a binary buffer directly:

```
uint8_t buffer[4] = {1, 2, 3, 4};
// This uses the send overload that takes a void * and length
s->send(hdl, buffer, sizeof(buffer), websocketpp::frame::opcode::binary);
```

For floats it is not generally safe to pack and send binary floating point data over a network to a different machine. This relies on the floating point representations and paddings being identical on different machines and operating systems.

If you are sending to/from Javascript and using Float32Array the format may be compatible with c/c++, in which case you can use the above syntax with floats. You will probably need to still deal with converting to/from network byte order in javascript and C++ for floats and ints greater than 1 byte each.

For more complex data or for a more elegant/high level solution I would recommend cross platform binary packing libraries like protocol buffers or msgpack.

If you have further questions about how to use the library, rather than ones reporting bugs, please use the mailing list (websocketpp@googlegroups.com) rather than Github issues.
