### ISSUE TITLE
Visual Studio 2013 : fatal error C1083: Cannot open include file: 'syslog.h': No such file or directory 

### ISSUE THREAD

**Issue by meiry** [zaphoyd/websocketpp#573]
Hello 
i tried to compile the framework using cmake 
the Visual Studio Solution files did generated but i have some problem with include file 
for example : 
```
fatal error C1083: Cannot open include file: 'syslog.h': No such file or directory
```
in the syslog.hpp
im not sure there is such file in Windows VS 2013

**Comment by meiry** [comment]
just comment it in windows seems to work

**Comment by zaphoyd** [comment]
WebSocket++ includes an optional syslog based logging policy. As syslog is POSIX specific, this logging policy doesn't work on Windows. It looks like one of the bundled debugging programs, that cmake is instructed to build on all platforms, makes use of this policy. I'll either remove that usage or add an exception so that this program doesn't get built on windows.

The issue with the example programs aside: The syslog policy cannot be used on Windows and the syslog policy is 100% optional. If you are writing programs using WebSocket++ that need to work on Windows, either don't use the syslog logger or include your own preprocessor config to selectively include.
