### ISSUE TITLE
control frames (especially close frames) are sent fragmented

### ISSUE THREAD

**Issue by Flow86** [zaphoyd/websocketpp#591]
Hi,

recently I got a strange issue with a websocket communication. Im still using 0.6 of websocketpp, but I think the bug is also in 0.7

The remote websocket only got a close frame of 2 bytes resulting in an "protocol error", since the status code in the payload are not processed.

The reason Ive found is that websocketpp violates RFC6455 "5.5 Control Frames"

> All control frames MUST have a payload length of 125 bytes or less and **MUST NOT be fragmented.**

The header and the payload of a control/close frame are sent seperately, not as "one" packet.

The Function async_write 
https://github.com/zaphoyd/websocketpp/blob/master/websocketpp/transport/asio/connection.hpp#L942
is called in write_frame
https://github.com/zaphoyd/websocketpp/blob/master/websocketpp/impl/connection_impl.hpp#L1833

with two buffers (header+payload) which result in fragmentation of the control frames

**Comment by zaphoyd** [comment]
The fragmentation referred to by RFC6455 as forbidden for control frames is WebSocket protocol fragmentation not TCP fragmentation. WebSocket++ performs writes logically from two separate buffers (header and payload) because the header length is variable and this avoids needing to copy the entire payload to be immediately after the header. If the transport policy supports it (the Asio one does) when actually written on the wire they are sent as a single TCP packet / TLS segment via scatter-gather/vectored I/O.

Per RFC6455 the close code and reason are optional. When not included the close frame will be exactly two bytes and this is legal and not a protocol error. WebSocket++ may or may not send a close code and/or text reason depending on what the end user asks for.

**Comment by Flow86** [comment]
Hi,
thanks for clarifying it. 

I think now that the other websocket-library (Starscream) does not handle TCP fragmentation correctly (thats why it does only receive the close frame header, not the payload) and additionally does not set the close-code correctly (no code is handled as protocol error which is wrong).
