### ISSUE TITLE
Threaded websocket server

### ISSUE THREAD

**Issue by Sfinx** [zaphoyd/websocketpp#62]
Hello,

Is it possible to use the websocketpp in threaded non-blocking server ? For example - each connection (and/or on_message event inside the connection event) process with new thread, so the stall/processing of the connections/events can't influence on others. As I understand - for now the default processing model is single threaded - the next connection or event inside connection will not be handled until the previous exits. This is very confusing for many applications.

Thanks

**Comment by alexkrasn** [comment]
Hi @zaphoyd ,
@Sfinx initially asked
> Hello,
> 
> Is it possible to use the websocketpp in threaded non-blocking server ? For example - each connection (and/or on_message event inside the connection event) process with new thread, so the stall/processing of the connections/events can't influence on others. As I understand - for now the default processing model is single threaded - the next connection or event inside connection will not be handled until the previous exits. This is very confusing for many applications.
> 
> Thanks

I see that this issue is listed as closed, however, I can't figure out the resolution.
My main issue is that I am using AutobahnCpp, which internally calls WebsocketPP to connect to a WAMP server. The connection happens appropriately and it seems to work, it even keeps track of messages when I add unnecessary delays, however, it seems to lose some messages (determined by missing sequence numbers) and it happens regardless of any added delays.

Thank you in advance,
Aleksandr
