### ISSUE TITLE
Implementing SSL 

### ISSUE THREAD

**Issue by poppedcorn** [zaphoyd/websocketpp#630]
I'm hoping for a little guidance as I've gotten myself stuck trying to implement SSL support in our server.  We swapped out our legacy Java applet for jQuery widgets that open a websocket connections to a server derived from websocket++. Everything works great. Now I'm trying to add SSL support and the approach I've taken is to use the same certificate that is security the IIS portal and use load_verify_file which succeeds. The widgets are using wss but the server reports "TLS handshake failed" on each connection. Am I taking the right approach? Can I reused that website certificate on the server? 

Thank you for your time. Love your software. 
James

**Comment by peererror** [comment]
if the website and your websocket server are on the same machine(server) than yes I think you can  use that but if they are on different servers(machine) than `you will  need separate certificates for each server.

**Comment by peererror** [comment]
and Also open https://websocket_server_ip:port/ and see what you get

**Comment by poppedcorn** [comment]
Here's the results. Could it be that the server is seeing the connection as an IP address and not a qualified domain?

Using https://jg2012.taske.com:9002/ browser console results:
https://jg2012.taske.com:9002/ Failed to load resource: net::ERR_CONNECTION_CLOSED
https://jg2012.taske.com:9002/:1 GET https://jg2012.taske.com:9002/ net::ERR_CONNECTION_CLOSED
https://jg2012.taske.com:9002/:1 GET https://jg2012.taske.com:9002/ net::ERR_CONNECTION_CLOSED
https://jg2012.taske.com:9002/:1 GET https://jg2012.taske.com:9002/ net::ERR_TIMED_OUT

Using https://192.168.21.84:9002/ browser console results:
https://192.168.21.84:9002/:1 GET https://192.168.21.84:9002/ net::ERR_CONNECTION_CLOSED
https://192.168.21.84:9002/:1 GET https://192.168.21.84:9002/ net::ERR_CONNECTION_CLOSED
https://192.168.21.84:9002/:1 GET https://192.168.21.84:9002/ net::ERR_CONNECTION_CLOSED
https://192.168.21.84:9002/:1 GET https://192.168.21.84:9002/ net::ERR_CONNECTION_CLOSED

Server results for both tests:
https://jg2012.taske.com:9002/
[2017-03-23 10:55:25] [error] handle_transport_init received error: TLS handshake failed
[2017-03-23 10:55:25] [fail] WebSocket Connection [::ffff:192.168.21.84]:52527 - "" - 0 websocketpp.transport.asio.socket:8 TLS handshake failed
... repeats

**Comment by zaphoyd** [comment]
You can definitely use the same certificate that you use for HTTPS for WSS. The WebSocket protocol handshake is valid HTTP. You will need to make sure that the certificate's name matches the hostname you are running the server on. So either using the same name but two different ports or a sub domain for WS where both the main name and sub domain are both listed on the certificate.

Its fine if the web server and web socket server are on different machines as long as the names/dns all check out on both machines. 

Behavior of browsers when they hit an untrusted WebSocket server (due to mismatched names, unsupported protocols, untrusted root/self signed) is generally to silently fail (as opposed to https which sometimes prompts a message to ignore). In some OSes you can explicitly trust a self signed cert elsewhere in the OS that will be respected by your browser to help with this.

Some thoughts:
You will want to make sure the certificate formats are compatible with OpenSSL. IIS may use a different encoding format. There are some free programs (some included with OpenSSL) that let you convert the cert to various formats. PEM is a good one for OpenSSL/WebSocket++.

A raw IP will generally be problematic because of the name mismatch issues. If you do that you'll need some way of getting the browser to trust it.

You may be able to get more answers from the server if you enable higher levels of logging. In particular You may be able to get the OpenSSL error code for why the handshake failed.

Another potential way of getting more information (especially about protocol level mismatches, untrusted carts, etc) is running the OpenSSL s_client application in verbose mode and connecting to the server.

**Comment by poppedcorn** [comment]
I spent the week doing a deep dive into the mechanics of SSL and eventually figured out that our key file was corrupt. I re-exported it. and was able to successfully communicate using the same cert/key pair that the IIS site used but with a different port. You're tips on s_client and s_server were invaluable.  Thank you.

Just to let you know, the certs used by IIS don't need conversion. They are standard syntax. 

Cheers
James

**Comment by zaphoyd** [comment]
Glad to know this was helpful. Closing this now.
