### ISSUE TITLE
simple client function for process ?

### ISSUE THREAD

**Issue by akeyliu** [zaphoyd/websocketpp#833]
As a user for websockpp, I'm now using it for http server, and it's great!!
Now, I need to add some process logic for http client,  and it's very complicated for the user to write many code for it.
I understand that websocketpp is mostly for server, but client is also often needed.
I find a httplib provide http client at https://github.com/yhirose/cpp-httplib.
It's very simple in it, just like this..
#include <httplib.h>
#include <iostream>
int main(void)
{
    httplib::Client cli("localhost", 1234);
    auto res = cli.Get("/hi");
    if (res && res->status == 200) {
        std::cout << res->body << std::endl;
    }
}

So, if websocketpp can also provide function like this? or some sample code for similar functions?

Thanks.

**Comment by zaphoyd** [comment]
WebSocket++ is primarily a WebSocket library. There are a lot of good HTTP libraries out there already. WebSocket++ in server mode does implement a limited HTTP handler because there are a number of use cases where it is useful for the program to be able to return HTTP error messages or host its own javascript client program on the same port that WebSockets are processed. This is somewhat more complicated to do with two separate server side libraries.

Generic HTTP client functionality is out of scope for WebSocket++. If you need HTTP client functionality I would recommend the path you've taken here, which is to pull in a dedicated HTTP client library and use that.
