### ISSUE TITLE
How to listen on multi ports in one main loop? Is there a per-loop callback available?

### ISSUE THREAD

**Issue by uniqss** [zaphoyd/websocketpp#853]
I am writing a gateway listening on multi ports for websocket connections, and a timer that must be called every loop. I don't want to use multi threads. Also I want to have a time manager that is not too precise which make a system call at the begining of every frame. The time manager also need to be called in the main loop. I just don't know how to listen on multi ports and how to execute my per-frame callback. Thanks very much!

**Comment by zaphoyd** [comment]
If you are using the Asio transport you can register WebSocket++ endpoints on an external/self managed `io_service` or `io_context`. This lets you register multiple endpoints (each can listen on a different port) on the same event loop. You can run your own timers via Asio on this event loop. If you prefer to use your own timer management and/or drive the event loop directly you can use Asio's various polling methods instead of `run()`. This lets you process a single event in the Asio loop, give Asio a rough amount of time to run as many handlers as it can, etc before returning back to your main loop to do other non-Asio tasks.

Take a look at the bundled `external_io_service` example for more details about using self managed `io_service` objects with WebSocket++. See the Asio documention for options for manually polling the Asio loop: https://www.boost.org/doc/libs/1_73_0/doc/html/boost_asio/reference/io_service.html
