### ISSUE TITLE
A probable bug in handling responses with headers that are not immediately ready

### ISSUE THREAD

**Issue by oleh-derevenko** [zaphoyd/websocketpp#899]
In impl/connection_impl.hpp lines 929 and 1651 there are 'else' clauses for conditionals testing  
'if (m_request.ready())' and 'if (m_response.headers_ready())'. These 'else' clauses schedule new asynchronous reads for the buffer discarding its content and not checking whether bytes_processed was actually equal to bytes_transferred. If that would not be the case, the remainder of the bytes_transferred is going to be lost.
I only had a quick review of the library source and not sure whether the situation described above could be possible indeed, but adding an assertion check, at least, would be nice.

**Comment by zaphoyd** [comment]
My understanding of this situation is that it is impossible for the HTTP message parser to leave information in the buffer that it still needs. Either all information is processed or the remaining information is illegal stray information (for example bytes in excess of the stated Content-Length header, which the library ignores or body bytes in the case that the library is only reading the headers).

An assertion that the HTTP parser must drain the buffer before asking to refill it seems reasonable and would fail quickly and precisely rather than corrupting data in the case of regressions or logic errors in the somewhat complex and lightly coupled HTTP parsers.
